# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: vue3
    env:
      DEV_PATH: /home/joo/vue3
      GIT_URL: git@github.com:fada2020/vue3.git
    strategy:
      matrix:
        node-version: [17.9.1]
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to server
        run: |
          mkdir -p ${{ env.DEV_PATH }} && cd ${{ env.DEV_PATH }}  # Create the directory if it doesn't exist
          if [ ! -d "${{ env.DEV_PATH }}/.git" ]; then
            git clone ${{ env.GIT_URL }} .
          else
            git pull ${{ env.GIT_URL }}  # 변경 사항을 가져오기 test
          fi
          npm install
          npm run build

          if ! sudo lsof -i :3000; then # 포트 3000을 사용하여 Vue.js 앱을 실행
           npm install @vue/cli
           npm run start &
          fi
